%Doctor.Config{
  ignore_modules: [
    String.Chars.Smee.Entity,
    String.Chars.Smee.Metadata,
    String.Chars.Smee.Source,
    Smee.XSLT,
    Smee.XPaths,
    Smee.XmlMunger,
    Smee.XmlCfg,
    Smee.Utils,
    Smee.SysCfg,
    Inspect.Smee.Metadata,
    Inspect.Smee.Entity,
    Jason.Encoder.Smee.Metadata,
    Jason.Encoder.Smee.Entity,
    Jason.Encoder.Smee.Source,
    Smee.SigningCertificate,
    Smee.Security.Xmlsectool,
    Smee.Security.Xmlsec1,
    Smee.Security.Mdqt,
    Smee.EasySSL
  ],
  ignore_paths: [],
  min_module_doc_coverage: 40,
  min_module_spec_coverage: 0,
  min_overall_doc_coverage: 50,
  min_overall_moduledoc_coverage: 100,
  min_overall_spec_coverage: 0,
  exception_moduledoc_required: true,
  raise: false,
  reporter: Doctor.Reporters.Full,
  struct_type_spec_required: true,
  umbrella: false,
  failed: false
}
